#spring:
#  data:
#    mongodb:
#      username: admin
#      password: pass
#      host: localhost
#      port: 27017
#      database: customer
#      authentication-database: admin
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer

server:
  port: 8090
